// Designing OpenMinds IDE/.storage/11/ea2ef3c4/DatasetViewer.tsx
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { SearchIcon, DownloadIcon, RefreshIcon, BarChart2Icon, TableIcon, FilterIcon } from "lucide-react";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export function DatasetViewer() {
  const [activeTab, setActiveTab] = useState("table");
  const [activeDataset, setActiveDataset] = useState("mnist");
  const [searchQuery, setSearchQuery] = useState("");
  const [page, setPage] = useState(1);
  
  // Sample dataset options
  const datasets = [
    { id: "mnist", name: "MNIST", rows: 70000, columns: 785, type: "Image Classification" },
    { id: "cifar10", name: "CIFAR-10", rows: 60000, columns: 3073, type: "Image Classification" },
    { id: "customer_data", name: "Customer Data", rows: 10000, columns: 15, type: "Tabular" },
    { id: "sentiment", name: "Sentiment Analysis", rows: 25000, columns: 3, type: "Text" },
  ];
  
  // Sample dataset data (for MNIST)
  const sampleData = {
    columns: ["id", "pixel1", "pixel2", "pixel3", "pixel4", "pixel5", "pixel6", "label"],
    rows: [
      [1, 0, 0, 0, 10, 12, 5, 5],
      [2, 0, 0, 8, 16, 9, 0, 0],
      [3, 0, 0, 0, 0, 5, 14, 1],
      [4, 0, 3, 10, 9, 5, 0, 9],
      [5, 0, 0, 0, 5, 12, 8, 3],
      [6, 0, 0, 0, 0, 0, 0, 6],
      [7, 0, 0, 7, 15, 13, 1, 8],
      [8, 0, 0, 0, 8, 13, 11, 2],
      [9, 0, 0, 0, 0, 10, 14, 7],
      [10, 0, 5, 12, 9, 2, 0, 4],
    ]
  };
  
  // Sample dataset statistics
  const datasetStats = {
    mnist: [
      { stat: "Mean", value: "0.1307" },
      { stat: "Std Dev", value: "0.3081" },
      { stat: "Min", value: "0" },
      { stat: "Max", value: "255" },
      { stat: "Missing Values", value: "0" },
      { stat: "Label Distribution", value: "Balanced" },
    ],
    cifar10: [
      { stat: "Mean", value: "0.4734" },
      { stat: "Std Dev", value: "0.2516" },
      { stat: "Min", value: "0" },
      { stat: "Max", value: "255" },
      { stat: "Missing Values", value: "0" },
      { stat: "Label Distribution", value: "Balanced" },
    ],
    customer_data: [
      { stat: "Mean Age", value: "34.6" },
      { stat: "Income Range", value: "$24k - $105k" },
      { stat: "Missing Values", value: "156" },
      { stat: "Categorical Features", value: "5" },
      { stat: "Numerical Features", value: "10" },
      { stat: "Target Distribution", value: "Imbalanced" },
    ],
    sentiment: [
      { stat: "Avg. Word Count", value: "87.3" },
      { stat: "Vocabulary Size", value: "24,987" },
      { stat: "Missing Values", value: "0" },
      { stat: "Sentiment Distribution", value: "Balanced" },
      { stat: "Languages", value: "English" },
      { stat: "Data Source", value: "IMDB Reviews" },
    ],
  };
  
  const currentDataset = datasets.find(d => d.id === activeDataset) || datasets[0];
  const currentStats = datasetStats[activeDataset as keyof typeof datasetStats] || [];
  
  return (
    <div className="flex flex-col h-full">
      {/* Dataset toolbar */}
      <div className="border-b p-2 flex items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <Select value={activeDataset} onValueChange={setActiveDataset}>
            <SelectTrigger className="w-[180px]">
              <SelectValue placeholder="Select Dataset" />
            </SelectTrigger>
            <SelectContent>
              {datasets.map((dataset) => (
                <SelectItem key={dataset.id} value={dataset.id}>
                  {dataset.name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          
          <div className="text-sm font-medium">
            {currentDataset.rows.toLocaleString()} rows × {currentDataset.columns} columns
          </div>
        </div>
        
        <div className="flex items-center gap-2">
          <div className="relative">
            <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Search data..."
              className="pl-9 h-9 w-[200px] md:w-[300px]"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
          </div>
          
          <Button size="sm" variant="outline">
            <FilterIcon className="h-4 w-4 mr-1" /> Filter
          </Button>
          
          <Button size="sm" variant="outline">
            <DownloadIcon className="h-4 w-4 mr-1" /> Export
          </Button>
          
          <Button size="sm" variant="ghost">
            <RefreshIcon className="h-4 w-4" />
          </Button>
        </div>
      </div>
      
      {/* Dataset view tabs */}
      <Tabs value={activeTab} onValueChange={setActiveTab} className="flex-1 flex flex-col">
        <div className="border-b">
          <TabsList>
            <TabsTrigger value="table">
              <TableIcon className="h-4 w-4 mr-1" /> Table View
            </TabsTrigger>
            <TabsTrigger value="stats">
              <BarChart2Icon className="h-4 w-4 mr-1" /> Statistics
            </TabsTrigger>
          </TabsList>
        </div>
        
        {/* Dataset views */}
        <div className="flex-1 overflow-hidden">
          <TabsContent value="table" className="h-full m-0">
            <ScrollArea className="h-full">
              <div className="p-4">
                <Table>
                  <TableHeader>
                    <TableRow>
                      {sampleData.columns.map((col, i) => (
                        <TableHead key={i} className={i === 0 ? "w-[80px]" : ""}>
                          {col}
                        </TableHead>
                      ))}
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {sampleData.rows.map((row, i) => (
                      <TableRow key={i}>
                        {row.map((cell, j) => (
                          <TableCell key={j}>{cell}</TableCell>
                        ))}
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
                
                {/* Pagination */}
                <div className="flex items-center justify-between mt-4">
                  <div className="text-sm text-muted-foreground">
                    Showing 1-10 of {currentDataset.rows.toLocaleString()} entries
                  </div>
                  <div className="flex items-center gap-1">
                    <Button 
                      size="sm" 
                      variant="outline" 
                      disabled={page === 1}
                      onClick={() => setPage(page - 1)}
                    >
                      Previous
                    </Button>
                    <Button 
                      size="sm" 
                      variant="outline"
                      onClick={() => setPage(page + 1)}
                    >
                      Next
                    </Button>
                  </div>
                </div>
              </div>
            </ScrollArea>
          </TabsContent>
          
          <TabsContent value="stats" className="h-full m-0 overflow-auto">
            <div className="p-4">
              <h2 className="text-lg font-semibold mb-4">{currentDataset.name} Statistics</h2>
              
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {/* Dataset summary */}
                <Card>
                  <CardHeader className="pb-2">
                    <CardTitle className="text-sm">Dataset Summary</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="text-sm">
                      <div className="grid grid-cols-2 gap-1">
                        <div className="font-medium">Dataset:</div>
                        <div>{currentDataset.name}</div>
                        
                        <div className="font-medium">Type:</div>
                        <div>{currentDataset.type}</div>
                        
                        <div className="font-medium">Size:</div>
                        <div>{currentDataset.rows.toLocaleString()} rows</div>
                        
                        <div className="font-medium">Features:</div>
                        <div>{currentDataset.columns - 1}</div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
                
                {/* Statistics */}
                <Card>
                  <CardHeader className="pb-2">
                    <CardTitle className="text-sm">Statistical Measures</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="text-sm">
                      <div className="grid grid-cols-2 gap-1">
                        {currentStats.slice(0, 6).map((stat, i) => (
                          <React.Fragment key={i}>
                            <div className="font-medium">{stat.stat}:</div>
                            <div>{stat.value}</div>
                          </React.Fragment>
                        ))}
                      </div>
                    </div>
                  </CardContent>
                </Card>
                
                {/* Distribution Chart Placeholder */}
                <Card>
                  <CardHeader className="pb-2">
                    <CardTitle className="text-sm">Label Distribution</CardTitle>
                  </CardHeader>
                  <CardContent className="flex items-center justify-center">
                    <div className="h-[150px] w-full text-center text-muted-foreground flex flex-col items-center justify-center border rounded">
                      <BarChart2Icon className="h-8 w-8 mb-2" />
                      <div className="text-sm">Chart visualization would appear here</div>
                    </div>
                  </CardContent>
                </Card>
              </div>
            </div>
          </TabsContent>
        </div>
      </Tabs>
    </div>
  );
}

// src/routes/lib/components/DatasetViewer.svelte
<script>
  import { onMount } from 'svelte';
  import { datasets } from '../stores.js';
  import { Search, Filter, Download, BarChart3, Table, Database } from 'lucide-svelte';

  let selectedDataset = $state(null);
  let viewMode = $state('table');
  let searchTerm = $state('');
  let currentPage = $state(1);
  let itemsPerPage = 50;
  
  // Mock data for demonstration
  let sampleData = [
    { id: 1, feature1: 1.2, feature2: 3.4, feature3: 5.6, feature4: 7.8, target: 0 },
    { id: 2, feature1: 2.1, feature2: 4.3, feature3: 6.5, feature4: 8.7, target: 1 },
    { id: 3, feature1: 3.2, feature2: 5.4, feature3: 7.6, feature4: 9.8, target: 0 },
    { id: 4, feature1: 4.3, feature2: 6.5, feature3: 8.7, feature4: 10.9, target: 1 },
    { id: 5, feature1: 5.4, feature2: 7.6, feature3: 9.8, feature4: 12.0, target: 0 }
  ];

  let datasetList = $state([]);
  datasets.subscribe(value => datasetList = value);

  onMount(() => {
    if (datasetList.length > 0) {
      selectedDataset = datasetList[0];
    }
  });

  function selectDataset(dataset) {
    selectedDataset = dataset;
  }

  function toggleViewMode() {
    viewMode = viewMode === 'table' ? 'chart' : 'table';
  }

  function exportData() {
    console.log('Exporting dataset:', selectedDataset?.name);
  }

  let filteredData = $derived(sampleData.filter(row => 
    Object.values(row).some(value => 
      value.toString().toLowerCase().includes(searchTerm.toLowerCase())
    )
  ));

  let paginatedData = $derived(filteredData.slice(
    (currentPage - 1) * itemsPerPage,
    currentPage * itemsPerPage
  ));

  let totalPages = $derived(Math.ceil(filteredData.length / itemsPerPage));
</script>

<div class="flex h-full">
  <!-- Dataset List Sidebar -->
  <div class="w-64 bg-gray-850 border-r border-gray-700 flex flex-col">
    <div class="p-4 border-b border-gray-700">
      <h3 class="font-semibold mb-3">Datasets</h3>
      <div class="space-y-2">
        {#each datasetList as dataset}
          <button 
            type="button"
            class="p-3 bg-gray-800 rounded cursor-pointer hover:bg-gray-700 {selectedDataset?.name === dataset.name ? 'ring-2 ring-blue-500' : ''}"
            onclick={() => selectDataset(dataset)}
            aria-label="Select dataset"
          >
            <div class="font-medium text-sm">{dataset.name}</div>
            <div class="text-xs text-gray-400 mt-1">
              {dataset.rows.toLocaleString()} rows • {dataset.columns} cols
            </div>
            <div class="text-xs text-gray-500">{dataset.size}</div>
          </button>
        {/each}
      </div>
    </div>

    <!-- Dataset Info -->
    {#if selectedDataset}
      <div class="p-4">
        <h4 class="font-medium mb-2">Dataset Info</h4>
        <div class="space-y-2 text-sm">
          <div class="flex justify-between">
            <span class="text-gray-400">Rows:</span>
            <span>{selectedDataset.rows.toLocaleString()}</span>
          </div>
          <div class="flex justify-between">
            <span class="text-gray-400">Columns:</span>
            <span>{selectedDataset.columns}</span>
          </div>
          <div class="flex justify-between">
            <span class="text-gray-400">Size:</span>
            <span>{selectedDataset.size}</span>
          </div>
          <div class="flex justify-between">
            <span class="text-gray-400">Modified:</span>
            <span>{selectedDataset.lastModified}</span>
          </div>
        </div>
      </div>
    {/if}
  </div>

  <!-- Main Content -->
  <div class="flex-1 flex flex-col">
    {#if selectedDataset}
      <!-- Toolbar -->
      <div class="h-12 bg-gray-800 border-b border-gray-700 flex items-center px-4 gap-4">
        <h2 class="font-semibold">{selectedDataset.name}</h2>
        
        <div class="flex-1"></div>
        
        <!-- Search -->
        <div class="relative">
          <Search size={16} class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
          <input 
            type="text" 
            placeholder="Search data..."
            class="pl-10 pr-4 py-2 bg-gray-700 border border-gray-600 rounded text-sm w-64"
            bind:value={searchTerm}
          />
        </div>

        <!-- View Toggle -->
        <button 
          type="button"
          class="flex items-center gap-2 px-3 py-2 bg-gray-700 hover:bg-gray-600 rounded text-sm"
          onclick={toggleViewMode}
          aria-label="Toggle view mode"
        >
          {#if viewMode === 'table'}
            <BarChart3 size={16} />
            Chart View
          {:else}
            <Table size={16} />
            Table View
          {/if}
        </button>

        <button 
          type="button"
          class="flex items-center gap-2 px-3 py-2 bg-blue-600 hover:bg-blue-700 rounded text-sm"
          aria-label="Filter data"
        >
          <Filter size={16} />
          Filter
        </button>

        <button 
          type="button"
          class="flex items-center gap-2 px-3 py-2 bg-green-600 hover:bg-green-700 rounded text-sm"
          onclick={exportData}
          aria-label="Export data"
        >
          <Download size={16} />
          Export
        </button>
      </div>

      <!-- Content Area -->
      <div class="flex-1 overflow-auto p-4">
        {#if viewMode === 'table'}
          <!-- Table View -->
          <div class="bg-gray-800 rounded-lg overflow-hidden">
            <div class="overflow-x-auto">
              <table class="w-full">
                <thead class="bg-gray-700">
                  <tr>
                    {#if paginatedData.length > 0}
                      {#each Object.keys(paginatedData[0]) as column}
                        <th class="px-4 py-3 text-left text-sm font-medium text-gray-300 uppercase tracking-wider">
                          {column}
                        </th>
                      {/each}
                    {/if}
                  </tr>
                </thead>
                <tbody class="divide-y divide-gray-700">
                  {#each paginatedData as row, i}
                    <tr class="hover:bg-gray-750">
                      {#each Object.values(row) as value}
                        <td class="px-4 py-3 text-sm text-gray-300">
                          {typeof value === 'number' ? value.toFixed(2) : value}
                        </td>
                      {/each}
                    </tr>
                  {/each}
                </tbody>
              </table>
            </div>
          </div>

          <!-- Pagination -->
          <div class="flex items-center justify-between mt-4">
            <div class="text-sm text-gray-400">
              Showing {(currentPage - 1) * itemsPerPage + 1} to {Math.min(currentPage * itemsPerPage, filteredData.length)} of {filteredData.length} results
            </div>
            <div class="flex gap-2">
              <button 
                type="button"
                class="px-3 py-1 bg-gray-700 hover:bg-gray-600 rounded text-sm disabled:opacity-50"
                disabled={currentPage === 1}
                onclick={() => currentPage = Math.max(1, currentPage - 1)}
                aria-label="Previous page"
              >
                Previous
              </button>
              <span class="px-3 py-1 bg-gray-800 rounded text-sm">
                {currentPage} of {totalPages}
              </span>
              <button 
                type="button"
                class="px-3 py-1 bg-gray-700 hover:bg-gray-600 rounded text-sm disabled:opacity-50"
                disabled={currentPage === totalPages}
                onclick={() => currentPage = Math.min(totalPages, currentPage + 1)}
                aria-label="Next page"
              >
                Next
              </button>
            </div>
          </div>
        {:else}
          <!-- Chart View -->
          <div class="grid grid-cols-2 gap-4">
            <div class="bg-gray-800 p-4 rounded-lg">
              <h3 class="font-medium mb-4">Feature Distribution</h3>
              <div class="h-64 flex items-center justify-center text-gray-400">
                <div class="text-center">
                  <BarChart3 size={48} class="mx-auto mb-2" />
                  <p>Chart visualization would be rendered here</p>
                  <p class="text-sm">Integration with Chart.js or D3.js</p>
                </div>
              </div>
            </div>
            <div class="bg-gray-800 p-4 rounded-lg">
              <h3 class="font-medium mb-4">Target Distribution</h3>
              <div class="h-64 flex items-center justify-center text-gray-400">
                <div class="text-center">
                  <BarChart3 size={48} class="mx-auto mb-2" />
                  <p>Pie chart would be rendered here</p>
                </div>
              </div>
            </div>
          </div>
        {/if}
      </div>
    {:else}
      <div class="flex-1 flex items-center justify-center">
        <div class="text-center text-gray-400">
          <Database size={64} class="mx-auto mb-4" />
          <h3 class="text-xl font-semibold mb-2">No Dataset Selected</h3>
          <p>Select a dataset from the sidebar to view its contents</p>
        </div>
      </div>
    {/if}
  </div>
</div>
